name: search_repositories
description: "github search repositories"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^15.1.1
  http: ^1.3.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  readmore: ^3.0.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  flutter_secure_storage: ^4.2.1
  fluttertoast: ^8.2.12
  shared_preferences: ^2.5.3
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  freezed: ^3.0.6
  riverpod_generator: ^2.0.0
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/github_icon/github-mark.png