name: search_repositories
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_hooks:
  hooks_riverpod:
  flutter_riverpod:
  riverpod_annotation:
  go_router: ^14.8.1
  http: ^1.3.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  readmore: ^3.0.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  flutter_secure_storage: ^9.2.4
  fluttertoast: ^8.2.12
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  freezed: ^3.0.6
  riverpod_generator:
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
